[package]
name = "jc-dict"
version = "0.4.0"
edition = "2021"

[dependencies]
rustyline = "9.1.2"
reqwest = "0.11.9"
tokio = { version = "1.17.0", features = ["full"] }
regex = "1.5.4"
rodio = "0.15.0"
colored = "2.0.0"
rusqlite = {version = "0.27.0", features = ["bundled"]}
dirs = "4.0.0"