name: wd_dict
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  args: ^2.3.0
  http: ^0.13.4
  colorize: ^3.0.0
  mp3_player: ^0.2.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
