name: jc-dict
version: 0.4.0
summary: CLI 有道词典
description: |
  无道词典 / CLI 有道词典 / Terminal Youdao Dictionary
  - English to Chinese lookup
  - Chinese to English lookup
  - Translation
  - Pronunciation playback
  - Similar words suggestions

base: core18
confinement: devmode

parts:
  jc-dict:
    plugin: dump
    source: ./jc.tar.xz
    # build-packages:
    #   - gcc
    #   - libasound2-dev
    #   - libopus-dev
    #   - libortp-dev
    stage-packages:
      - libasound2
      # - libopus0
      # - libortp9

apps:
  jc:
    command: jc
    plugs:
      # - alsa
      # - audio-playback
      # - pulseaudio
  jc-dict:
    command: jc

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
# sudo snap remove jc-dict && rm jc-dictionary-cli_*.snap
# snapcraft
# sudo snap install jc-dictionary-cli_*.snap --devmode --dangerous
